/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as indexRouteImport } from './routes/index'
import { Route as ApiInboxRouteImport } from './../inbox/routes/inbox'
import { Route as ApiWorkspaceRouteImport } from './routes/api/workspace'
import { Route as ApiChannelsChannelIdRouteImport } from './../channels/routes/channels/$channelId'
import { Route as ApiServeScopeSplatRouteImport } from './../files/routes/serve/$scope/$'
import { Route as ApiWatchScopeSplatRouteImport } from './../files/routes/watch/$scope/$'

const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInboxRoute = ApiInboxRouteImport.update({
  id: '/api/inbox',
  path: '/api/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceRoute = ApiWorkspaceRouteImport.update({
  id: '/api/workspace',
  path: '/api/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelsChannelIdRoute = ApiChannelsChannelIdRouteImport.update({
  id: '/api/channels/$channelId',
  path: '/api/channels/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServeScopeSplatRoute = ApiServeScopeSplatRouteImport.update({
  id: '/api/serve/$scope/$',
  path: '/api/serve/$scope/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchScopeSplatRoute = ApiWatchScopeSplatRouteImport.update({
  id: '/api/watch/$scope/$',
  path: '/api/watch/$scope/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/api/channels/$channelId': typeof ApiChannelsChannelIdRoute
  '/api/serve/$scope/$': typeof ApiServeScopeSplatRoute
  '/api/watch/$scope/$': typeof ApiWatchScopeSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof indexRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/api/channels/$channelId': typeof ApiChannelsChannelIdRoute
  '/api/serve/$scope/$': typeof ApiServeScopeSplatRoute
  '/api/watch/$scope/$': typeof ApiWatchScopeSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof indexRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/api/channels/$channelId': typeof ApiChannelsChannelIdRoute
  '/api/serve/$scope/$': typeof ApiServeScopeSplatRoute
  '/api/watch/$scope/$': typeof ApiWatchScopeSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/inbox'
    | '/api/workspace'
    | '/api/channels/$channelId'
    | '/api/serve/$scope/$'
    | '/api/watch/$scope/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/inbox'
    | '/api/workspace'
    | '/api/channels/$channelId'
    | '/api/serve/$scope/$'
    | '/api/watch/$scope/$'
  id:
    | '__root__'
    | '/'
    | '/api/inbox'
    | '/api/workspace'
    | '/api/channels/$channelId'
    | '/api/serve/$scope/$'
    | '/api/watch/$scope/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute
  ApiInboxRoute: typeof ApiInboxRoute
  ApiWorkspaceRoute: typeof ApiWorkspaceRoute
  ApiChannelsChannelIdRoute: typeof ApiChannelsChannelIdRoute
  ApiServeScopeSplatRoute: typeof ApiServeScopeSplatRoute
  ApiWatchScopeSplatRoute: typeof ApiWatchScopeSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbox': {
      id: '/api/inbox'
      path: '/api/inbox'
      fullPath: '/api/inbox'
      preLoaderRoute: typeof ApiInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace': {
      id: '/api/workspace'
      path: '/api/workspace'
      fullPath: '/api/workspace'
      preLoaderRoute: typeof ApiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channels/$channelId': {
      id: '/api/channels/$channelId'
      path: '/api/channels/$channelId'
      fullPath: '/api/channels/$channelId'
      preLoaderRoute: typeof ApiChannelsChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/serve/$scope/$': {
      id: '/api/serve/$scope/$'
      path: '/api/serve/$scope/$'
      fullPath: '/api/serve/$scope/$'
      preLoaderRoute: typeof ApiServeScopeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watch/$scope/$': {
      id: '/api/watch/$scope/$'
      path: '/api/watch/$scope/$'
      fullPath: '/api/watch/$scope/$'
      preLoaderRoute: typeof ApiWatchScopeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  ApiInboxRoute: ApiInboxRoute,
  ApiWorkspaceRoute: ApiWorkspaceRoute,
  ApiChannelsChannelIdRoute: ApiChannelsChannelIdRoute,
  ApiServeScopeSplatRoute: ApiServeScopeSplatRoute,
  ApiWatchScopeSplatRoute: ApiWatchScopeSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
