import {
  Archive,
  ArrowLeft,
  ArrowRight,
  Bot,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleDot,
  Clock,
  Feather,
  File,
  FolderOpen,
  GripVertical,
  Kanban,
  Loader2,
  MessageSquare,
  MoreHorizontal,
  PanelTop,
  Pencil,
  Plus,
  Regex,
  Search,
  Settings,
  Sparkles,
  Trash2,
  X,
  type LucideIcon,
} from "lucide-react";
import type { AppIconName } from "@apps/model/icons";

/** Browser components exposed to trusted app definitions and their host chrome. */
export const APP_ICONS = {
  Archive,
  ArrowLeft,
  ArrowRight,
  Bot,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleDot,
  Clock,
  Feather,
  File,
  FolderOpen,
  GripVertical,
  Kanban,
  Loader2,
  MessageSquare,
  MoreHorizontal,
  PanelTop,
  Pencil,
  Plus,
  Regex,
  Search,
  Settings,
  Sparkles,
  Trash2,
  X,
} satisfies Record<AppIconName, LucideIcon>;
