/**
 * The public Intent domain model: one flexible `IntentDocument`, its findings,
 * derived effective spec, and the optional execution plan that makes the spec
 * executable. Editor surfaces consume this facade; internal modules import their
 * source owner.
 */

export {
  INTENT_CHANGES,
  parseIntent,
  serializeIntent,
  type Change,
  type MarkdownSection,
  type ListSection,
  type Finding,
  type FindingUpdate,
  type FindingsSection,
  type IntentRecord,
  type IntentRecordUpdate,
  type OptionAddition,
  type RecordsSection,
  type RecordsView,
  type FlowNode,
  type FlowConnection,
  type FlowPath,
  type FlowRegion,
  type FlowExhibit,
  type TreeChange,
  type FileTreeEntry,
  type DomainTreeEntry,
  type TreeExhibit,
  type IntentExhibit,
  type IntentExhibitUpdate,
  type ExhibitsSection,
  type DefinitionSection,
  type Question,
  type DecisionOption,
  type DecisionChoice,
  type DecisionStatus,
  type Decision,
  type ResolutionSection,
  type SpecSection,
  type PlanPhase,
  type PlanSection,
  type PlanStep,
  type PlanStepStatus,
  type PlanStepUpdate,
  type IntentDocument,
  type IntentEntityId,
  type IntentField,
  type OptionRelationship,
  type SourcePolicy,
  type IntentSection,
  type IntentTab,
} from "./schema";

export {
  allDecisions,
  allFindings,
  allQuestions,
  activeOptionRelationships,
  decisionOriginForRecord,
  decisionStatus,
  fieldValueText,
  findExhibitsSection,
  findFindingsSection,
  findIntentEntity,
  findRecordsSection,
  intentEntities,
  entitiesGroundedByFinding,
  findingsForEntity,
  projectedRecords,
  recordLabel,
  recordReadingFields,
  resolveIntentTabs,
  selectedDecisionOption,
  selectedAdditions,
  type IntentEntity,
  type ActiveOptionRelationship,
  type ProjectedRecord,
  type ResolvedIntentTab,
} from "./query/reading";

export {
  entityFlowConnections,
  flowGraph,
  flowNodeId,
  flowPathSelectionAfterInspection,
  specState,
  unresolvedDependencies,
  type EntityFlowConnection,
  type FlowGraph,
  type FlowGraphNode,
  type SpecState,
} from "./spec";

export {
  planSections,
  planState,
  planStatus,
  planSteps,
  type PlanState,
  type PlanStatus,
} from "./plan";
