/**
 * The public Brief domain model: one flexible `BriefDocument`, its findings,
 * derived effective spec, and the optional execution plan that makes the spec
 * executable. Editor surfaces consume this facade; internal modules import their
 * source owner.
 */

export {
  BRIEF_CHANGES,
  parseBrief,
  serializeBrief,
  type Change,
  type MarkdownSection,
  type ListSection,
  type Finding,
  type FindingUpdate,
  type FindingsSection,
  type BriefRecord,
  type BriefRecordUpdate,
  type OptionAddition,
  type RecordsSection,
  type RecordsView,
  type FlowNode,
  type FlowConnection,
  type FlowPath,
  type FlowRegion,
  type FlowExhibit,
  type TreeChange,
  type FileTreeEntry,
  type DomainTreeEntry,
  type TreeExhibit,
  type BriefExhibit,
  type BriefExhibitUpdate,
  type ExhibitsSection,
  type DefinitionSection,
  type Question,
  type DecisionOption,
  type DecisionChoice,
  type DecisionStatus,
  type Decision,
  type ResolutionSection,
  type SpecSection,
  type PlanPhase,
  type PlanSection,
  type PlanStep,
  type PlanStepStatus,
  type PlanStepUpdate,
  type BriefDocument,
  type BriefEntityId,
  type BriefField,
  type OptionRelationship,
  type SourcePolicy,
  type BriefSection,
  type BriefTab,
} from "./schema";

export {
  allDecisions,
  allFindings,
  allQuestions,
  activeOptionRelationships,
  decisionOriginForRecord,
  decisionStatus,
  fieldValueText,
  findExhibitsSection,
  findFindingsSection,
  findBriefEntity,
  findRecordsSection,
  briefEntities,
  entitiesGroundedByFinding,
  findingsForEntity,
  projectedRecords,
  recordLabel,
  recordReadingFields,
  resolveBriefTabs,
  selectedDecisionOption,
  selectedAdditions,
  type BriefEntity,
  type ActiveOptionRelationship,
  type ProjectedRecord,
  type ResolvedBriefTab,
} from "./query/reading";

export {
  entityFlowConnections,
  flowGraph,
  flowNodeId,
  flowPathSelectionAfterInspection,
  specState,
  unresolvedDependencies,
  type EntityFlowConnection,
  type FlowGraph,
  type FlowGraphNode,
  type SpecState,
} from "./spec";

export {
  planSections,
  planState,
  planStatus,
  planSteps,
  type PlanState,
  type PlanStatus,
} from "./plan";
