export const APP_ICON_NAMES = [
  "Archive",
  "ArrowLeft",
  "ArrowRight",
  "Bot",
  "Check",
  "ChevronDown",
  "ChevronLeft",
  "ChevronRight",
  "Circle",
  "CircleDot",
  "Clock",
  "Feather",
  "File",
  "FolderOpen",
  "GripVertical",
  "Kanban",
  "Loader2",
  "MessageSquare",
  "MoreHorizontal",
  "PanelTop",
  "Pencil",
  "Plus",
  "Regex",
  "Search",
  "Settings",
  "Sparkles",
  "Trash2",
  "X",
] as const;

export type AppIconName = (typeof APP_ICON_NAMES)[number];
