/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWorkspaceRouteImport } from './routes/api/workspace'
import { Route as ApiInboxRouteImport } from './routes/api/inbox'
import { Route as ApiWatchSessionIdSplatRouteImport } from './routes/api/watch/$sessionId/$'
import { Route as ApiServeSessionIdSplatRouteImport } from './routes/api/serve/$sessionId/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceRoute = ApiWorkspaceRouteImport.update({
  id: '/api/workspace',
  path: '/api/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInboxRoute = ApiInboxRouteImport.update({
  id: '/api/inbox',
  path: '/api/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchSessionIdSplatRoute = ApiWatchSessionIdSplatRouteImport.update({
  id: '/api/watch/$sessionId/$',
  path: '/api/watch/$sessionId/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServeSessionIdSplatRoute = ApiServeSessionIdSplatRouteImport.update({
  id: '/api/serve/$sessionId/$',
  path: '/api/serve/$sessionId/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/api/serve/$sessionId/$': typeof ApiServeSessionIdSplatRoute
  '/api/watch/$sessionId/$': typeof ApiWatchSessionIdSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/api/serve/$sessionId/$': typeof ApiServeSessionIdSplatRoute
  '/api/watch/$sessionId/$': typeof ApiWatchSessionIdSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/api/serve/$sessionId/$': typeof ApiServeSessionIdSplatRoute
  '/api/watch/$sessionId/$': typeof ApiWatchSessionIdSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/inbox'
    | '/api/workspace'
    | '/api/serve/$sessionId/$'
    | '/api/watch/$sessionId/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/inbox'
    | '/api/workspace'
    | '/api/serve/$sessionId/$'
    | '/api/watch/$sessionId/$'
  id:
    | '__root__'
    | '/'
    | '/api/inbox'
    | '/api/workspace'
    | '/api/serve/$sessionId/$'
    | '/api/watch/$sessionId/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiInboxRoute: typeof ApiInboxRoute
  ApiWorkspaceRoute: typeof ApiWorkspaceRoute
  ApiServeSessionIdSplatRoute: typeof ApiServeSessionIdSplatRoute
  ApiWatchSessionIdSplatRoute: typeof ApiWatchSessionIdSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace': {
      id: '/api/workspace'
      path: '/api/workspace'
      fullPath: '/api/workspace'
      preLoaderRoute: typeof ApiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbox': {
      id: '/api/inbox'
      path: '/api/inbox'
      fullPath: '/api/inbox'
      preLoaderRoute: typeof ApiInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watch/$sessionId/$': {
      id: '/api/watch/$sessionId/$'
      path: '/api/watch/$sessionId/$'
      fullPath: '/api/watch/$sessionId/$'
      preLoaderRoute: typeof ApiWatchSessionIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/serve/$sessionId/$': {
      id: '/api/serve/$sessionId/$'
      path: '/api/serve/$sessionId/$'
      fullPath: '/api/serve/$sessionId/$'
      preLoaderRoute: typeof ApiServeSessionIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiInboxRoute: ApiInboxRoute,
  ApiWorkspaceRoute: ApiWorkspaceRoute,
  ApiServeSessionIdSplatRoute: ApiServeSessionIdSplatRoute,
  ApiWatchSessionIdSplatRoute: ApiWatchSessionIdSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
